import { StyleSheet } from 'react-native'

export const globalStyles = StyleSheet.create({
  modalContainer: {
    alignItems: 'stretch',
    padding: 15,
    borderWidth: 1.5,
    borderRadius: 15,
    borderColor: '#e0a8f7',
    borderTopWidth: 25,
    backgroundColor: 'white',
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 2,
    shadowOpacity: 0.5,
    shadowColor: '#e0a8f7',
  },
  modalTitle: {
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 15,
    fontSize: 24,
    fontWeight: 'bold',
  },
  defaultTextInput: {
    alignItems: 'center',
    width: '100%',
    minHeight: 40,
    marginBottom: 15,
    padding: 10,
    paddingVertical: 10,
    fontSize: 14,
    textDecorationLine: 'none',
    lineHeight: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e0a8f7',
    backgroundColor: 'white',
    // flex: 1,
    // width: "100%",
    // fontSize: 20,
    // alignContent: "flex-start",
    // justifyContent: "flex-start",
    // textAlignVertical: "top",
    // margin: 12
  },
  btn: {
    alignItems: 'center',
    height: 40,
    marginBottom: 15,
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#e0a8f7',
  },
  btnText: {
    color: 'white',
  },
})