import { StyleSheet } from 'react-native'

export const globalStyles = StyleSheet.create({
  modalContainer: {
    alignItems: 'stretch',
    padding: 15,
    borderWidth: 1.5,
    borderRadius: 15,
    borderColor: '#9B59B6',
    borderTopWidth: 25,
    backgroundColor: 'white',
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 2,
    shadowOpacity: 0.5,
    shadowColor: '#9B59B6',
  },
  modalTitle: {
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 15,
    fontSize: 24,
    fontWeight: 'bold',
  },
  defaultTextInput: {
    alignItems: 'center',
    width: '100%',
    minHeight: 40,
    marginBottom: 15,
    padding: 10,
    paddingVertical: 10,
    fontSize: 14,
    textDecorationLine: 'none',
    lineHeight: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#9B59B6',
    backgroundColor: 'white',
  },
  btn: {
    alignItems: 'center',
    height: 40,
    marginBottom: 15,
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#9B59B6',
  },
  btnText: {
    color: 'white',
  },
})